# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/workspace/3D_Object_Tracking

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/workspace/3D_Object_Tracking/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/workspace/3D_Object_Tracking/build/CMakeFiles /home/workspace/3D_Object_Tracking/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/workspace/3D_Object_Tracking/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3D_object_tracking

# Build rule for target.
3D_object_tracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3D_object_tracking
.PHONY : 3D_object_tracking

# fast build rule for target.
3D_object_tracking/fast:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/build
.PHONY : 3D_object_tracking/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/camFusion.o: src/camFusion.cpp.o

.PHONY : src/camFusion.o

# target to build an object file
src/camFusion.cpp.o:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/camFusion.cpp.o
.PHONY : src/camFusion.cpp.o

src/camFusion.i: src/camFusion.cpp.i

.PHONY : src/camFusion.i

# target to preprocess a source file
src/camFusion.cpp.i:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/camFusion.cpp.i
.PHONY : src/camFusion.cpp.i

src/camFusion.s: src/camFusion.cpp.s

.PHONY : src/camFusion.s

# target to generate assembly for a file
src/camFusion.cpp.s:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/camFusion.cpp.s
.PHONY : src/camFusion.cpp.s

src/lidarData.o: src/lidarData.cpp.o

.PHONY : src/lidarData.o

# target to build an object file
src/lidarData.cpp.o:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/lidarData.cpp.o
.PHONY : src/lidarData.cpp.o

src/lidarData.i: src/lidarData.cpp.i

.PHONY : src/lidarData.i

# target to preprocess a source file
src/lidarData.cpp.i:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/lidarData.cpp.i
.PHONY : src/lidarData.cpp.i

src/lidarData.s: src/lidarData.cpp.s

.PHONY : src/lidarData.s

# target to generate assembly for a file
src/lidarData.cpp.s:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/lidarData.cpp.s
.PHONY : src/lidarData.cpp.s

src/matching2D.o: src/matching2D.cpp.o

.PHONY : src/matching2D.o

# target to build an object file
src/matching2D.cpp.o:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/matching2D.cpp.o
.PHONY : src/matching2D.cpp.o

src/matching2D.i: src/matching2D.cpp.i

.PHONY : src/matching2D.i

# target to preprocess a source file
src/matching2D.cpp.i:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/matching2D.cpp.i
.PHONY : src/matching2D.cpp.i

src/matching2D.s: src/matching2D.cpp.s

.PHONY : src/matching2D.s

# target to generate assembly for a file
src/matching2D.cpp.s:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/matching2D.cpp.s
.PHONY : src/matching2D.cpp.s

src/objectDetection2D.o: src/objectDetection2D.cpp.o

.PHONY : src/objectDetection2D.o

# target to build an object file
src/objectDetection2D.cpp.o:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/objectDetection2D.cpp.o
.PHONY : src/objectDetection2D.cpp.o

src/objectDetection2D.i: src/objectDetection2D.cpp.i

.PHONY : src/objectDetection2D.i

# target to preprocess a source file
src/objectDetection2D.cpp.i:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/objectDetection2D.cpp.i
.PHONY : src/objectDetection2D.cpp.i

src/objectDetection2D.s: src/objectDetection2D.cpp.s

.PHONY : src/objectDetection2D.s

# target to generate assembly for a file
src/objectDetection2D.cpp.s:
	$(MAKE) -f CMakeFiles/3D_object_tracking.dir/build.make CMakeFiles/3D_object_tracking.dir/src/objectDetection2D.cpp.s
.PHONY : src/objectDetection2D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... 3D_object_tracking"
	@echo "... edit_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/camFusion.o"
	@echo "... src/camFusion.i"
	@echo "... src/camFusion.s"
	@echo "... src/lidarData.o"
	@echo "... src/lidarData.i"
	@echo "... src/lidarData.s"
	@echo "... src/matching2D.o"
	@echo "... src/matching2D.i"
	@echo "... src/matching2D.s"
	@echo "... src/objectDetection2D.o"
	@echo "... src/objectDetection2D.i"
	@echo "... src/objectDetection2D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

